export const types = {
  FETCH_SINGLE_MEAL_SUCCESS: "FETCH_SINGLE_MEAL_SUCCESS",

  POST_NEW_MEAL_PENDING: "POST_NEW_MEAL_PENDING",
  POST_NEW_MEAL_SUCCESS: "POST_NEW_MEAL_SUCCESS",
  POST_NEW_MEAL_ERROR: "POST_NEW_MEAL_ERROR",
};
